### PR TITLE
Multiple fixes for compatibility with other mods.

### PR DESCRIPTION
**Pull request by YPetremann**
Add multiple compatibility for other mods :
- for items not usable like trains (electric trains), cars (AAI mods), planners (upgrade planners, picker-extended)
- for mods adding multiple surfaces like factorissimo

### CODE REVIEW

**Comment by canidae** [comment]
Interesting changes. I'll have to go through them in detail later, but there are many good changes here I'd like to merge in.

**Comment by canidae** [comment]
Still haven't been able to test your changes, but I have some feedback after reading the code:
* Type placement in general is a better approach, although I'm curious if allowing all selection tools may break the scenario. For example, did you test this with the Upgrade Planner mod? The scenario turns on cheat mode, and the Upgrade Planner replaces entities for free in cheat mode.
* I'm not sure what I feel about giving the player a pumpjack at spawn point. I still feel the player should start without any resource producing entities (well, with the exception of some electricity). I was never really happy about placing some oil wells nearby either, but I'm not sure if your solution is better.
* Concrete beneath the starting structures I've considered and tried many times, but I always end up preferring the raw ground (while adding dirt if there's water in the way).
* As for Factorissimo, I have some other ideas, but supporting this mod is a bit down on my priority list. Instead of letting the user carry some resources I'm thinking of a "staging" area outside the factory where duplicates of ghosts placed inside the factory appear. When conbots construct the entities outside the factory the entities get "teleported" inside the factory.

I also noticed that you're using tabs instead of spaces for indentation, and your coding style differs from mine in some aspects (notably: I prefer keeping everything within an "if" to stay on one line, while you use multiple lines). Which style is better is obviously a subjective matter, but I'm not a fan of mixed coding style within the same project, so I encourage you to match the coding style as closely as possible when you send pull requests.

**Comment by YPetremann** [comment]
Well ... to make the points :
- I think that the function should work based on conditions to whitelist/blacklist items, in fact I didn't tested the upgrade planner, I did this mainly to allow pickerextended tools and thinking it would allow other planners from other mods.
- For the pumpjack, it turns out that the commit was intended for another pull request, but after all I though it would not be for the bad, but mainly if that not the pumpjack, I would keep that placement for all the objects, maybe replacing the pumpjack and storage tank with something else. I was thinking about another aproach that would fit player choice, basicaly, the chest contain some necessary items and coins, and they have access to the market, this one would permit to purchase some items (mainly assembling machines and roboports, maybe something more) in exchange of the coins.
- Same for concrete, it was an idea for the next pull request. I was also trying some dynamic placement that would autodiscover of what the floor is done else than water and place this instead of one predetermined, and using concrete if nothing is found (there is only water under the starting structure)
- For the factorissimo problem, I think that a big one is about other surfaces mods,, if it's compatible with factorissimo, it would not surely be with for example free real estate or subsurfaces, for now I only think of another way with only blueprint, mainly it would be the same idea but instead of allowing to get the item, there would be a requester chest in the starting area, if the player place the first ghosts of a surface, and no robots can build them, then the requester chest would request some items to build a roboport, a storage-chest, an electric-pole and a source of power, when they are recevied in the chest, it will place them without robots, it would request a construction-robot that it would place inside the roboport.

Sorry for the coding style it was not intended to change it, simply prefer tabs

**Comment by canidae** [comment]
I manually merged your first commit (checking item/placement type) and made some minor changes to it (like blocking the upgrade planner tool).
The other commits I can't accept as they are. While I'd like to see support for Factorissimo and other multi-surface mods, this approach is not how I'd like it solved.

**Pull request closed without merging**
